name: 'polymer_flex_components'
version: 0.0.1
description: A web app built using polymer.dart.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  browser: any
  browser_detect: any
  animation: any
  intl: any
  quiver: any
#  barback: any
  autonotify_observe: any
  polymer: ">=1.0.0-rc.15"
dev_dependencies:
  test: "^0.12.5+1"
  polymer_elements: ">=0.3.0"
  html: any
transformers:
- autonotify_observe:
   entry_points:
    - web/index.html
    - test/all_test.html
- test/pub_serve:
   $include: test/**_test{.*,}.dart
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: false
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
